### ISSUE TITLE
Relicensing

### ISSUE THREAD

**Issue by fleaz** [fleaz/CptHook#52]
Hey,

I would like to re-license CptHook under MIT, but because contributions from other people made to the project in the past are automatically also AGPL, I can't decide that on my own. Therefore I would like to hear your opinion and if you are fine with this?

@mweinelt 
@fooker 
@ManiacTwister

**Comment by fooker** [comment]
I'm ok with it.

**Comment by mweinelt** [comment]
ACK.

**Comment by ManiacTwister** [comment]
Sure, go ahead.

**Comment by fleaz** [comment]
Thanks everybody :)
