### ISSUE TITLE
GitLab: Match most specific namespace, not first one

### ISSUE THREAD

**Issue by mweinelt** [fleaz/CptHook#55]
For `"path_with_namespace": "ffda/infra/salt",` there is a difference between the following config snippets. Currently the first match is preferred over that with the longest matching prefix.

```
          'ffda':
            - '#ffda'
          'ffda/infra':
            - '#ffda-infra'
```

and 

```
          'ffda/infra':
            - '#ffda-infra'
          'ffda':
            - '#ffda'
```

**Comment by fleaz** [comment]
Sound like a sane behaviour. Will try to implement it soon'ish :D
